Pokedex/Models/Pokemon.cs
using System;
namespace Pokedex.Models
{
    public class Pokemon
    {
        public int PokemonId { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Categoria { get; set; }
        public double? BaseExperiencia { get; set; }
        public double? Peso { get; set; }
        public double? Altura { get; set; }
        public string Tipo1 { get; set; }
        public string Tipo2 { get; set; }
        public string Habilidade1 { get; set; }
        public string Habilidade2 { get; set; }
        public string Movimento1 { get; set; }
        public string Movimento2 { get; set; }
        public string Movimento3 { get; set; }
        public string Movimento4 { get; set; }
        public string Url_Pokemon { get; set; }
        public string Url_Sprite_front_default { get; set; }
        public string Url_Sprite_back_default { get; set; }
        public string Url_Sprite_back_female { get; set; }
        public string Url_Sprite_front_female { get; set; }
    }
}

Pokedex/Controllers/PokemonController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Pokedex.Dados.EntityFramework.Comum;
using Pokedex.Models;
using static Pokedex.Utilidades;

namespace Pokedex.Controllers
{
    public class PokemonController : Controller
    {
        Usuario user = new Usuario();
        public IActionResult Visualizar(int id)
        {
            Contexto db = new Contexto();
            user = db.Usuario.Find(id);
            if (user == null)
            {
                return RedirectToAction("Index","Home");
            }
            List<Pokemon> Pokemons = primeiraLetraMaiuscula( db.Pokemon.ToList());
            user.Nome = primeiraLetraMaiuscula(user.Nome);
            ViewBag.Usuario = user;
            return View(Pokemons);
        }
        public IActionResult Detalhes(int id, int usuarioid)
        {
            Contexto db = new Contexto();
            Pokemon pokemon = db.Pokemon.Find(id);
            pokemon.Altura = pokemon.Altura * 10;
            pokemon.Nome = primeiraLetraMaiuscula(pokemon.Nome);
            user = db.Usuario.Find(usuarioid);
            user.Nome = primeiraLetraMaiuscula(user.Nome);
            user.Pokemon = db.Pokemon.Find(user.PokemonId);

            ViewBag.Usuario = user;
            return View(pokemon);
        }
    }
}

Pokedex/Views/Pokemon/Detalhes.cshtml
@model Pokedex.Models.Pokemon

@{
    ViewData["Title"] = "Detalhes";
    ViewData["URL"] = ViewBag.Usuario.Pokemon.Url_Sprite_front_default;
    ViewData["Nome"] = ViewBag.Usuario.Nome;
    ViewData["UsuarioID"] = ViewBag.Usuario.UsuarioID;
}

<h3>Detalhes</h3>
<br />

<div>
    @Html.ActionLink("Meu Perfil", "Detalhes", "Usuario", new { id = ViewBag.usuarioid }, new { @class = "btn btn-outline-primary" })
    @Html.ActionLink("Pokédex", "Visualizar", "Pokemon", new { id = ViewBag.usuarioid }, new { @class = "btn btn-outline-danger" })
</div>

<div>
    <hr />
<h4>@Model.Nome</h4>
    <dl class="row">
        <dt class="col-sm-2">
            Sprite
        </dt>
        <dd class="col-sm-10">
            <img height="200" src="@Url.Content(Model.Url_Sprite_front_default)" alt="Sprite Frontal Default" />
            <img height="200" src="@Url.Content(Model.Url_Sprite_back_default)" alt="Sprite Frontal Default" />
            <img height="200" src="@Url.Content(Model.Url_Sprite_front_female)" alt="Sprite Frontal Feminino" />
            <img height="200" src="@Url.Content(Model.Url_Sprite_back_female)" alt="Sprite Frontal Feminino" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            Descrição
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Categoria)
        </dd>
        <dt class="col-sm-2">
            Base De Experiência
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BaseExperiencia)
        </dd>
        <dt class="col-sm-2">
            Peso
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Peso) Kg
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Altura)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Altura) cm
        </dd>
        <dt class="col-sm-2">
          Tipo 1
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tipo1)
        </dd>
        <dt class="col-sm-2">
            Tipo 2
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tipo2)
        </dd>
        <dt class="col-sm-2">
           Habilidade 1
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Habilidade1)
        </dd>
        <dt class="col-sm-2">
            Habilidade 2
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Habilidade2)
        </dd>
        <dt class="col-sm-2">
           Movimento 1
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movimento1)
        </dd>
        <dt class="col-sm-2">
            Movimento 2
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movimento2)
        </dd>
        <dt class="col-sm-2">
            Movimento 3
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movimento3)
        </dd>
        <dt class="col-sm-2">
            Movimento 4
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movimento4)
        </dd>

    </dl>
</div>

Pokedex/Views/Pokemon/Visualizar.cshtml
@model List<Pokedex.Models.Pokemon>
@{
    ViewData["URL"] = ViewBag.Usuario.Pokemon.Url_Sprite_front_default;
    ViewData["Nome"] = ViewBag.Usuario.Nome;
    ViewData["UsuarioID"] = ViewBag.Usuario.UsuarioID;
}


<h2>Pokedex (NatinalDex)</h2>
@Html.ActionLink("Meu Perfil", "Detalhes", "Usuario", new { id = ViewBag.Usuario.UsuarioID }, new { @class = "btn btn-outline-primary" })
<table class="table table-striped table-hover">
    <thead style="text-align:center">
        <tr>
            <th>
                Pokémon ID
            </th>
            <th>
                Sprite
            </th>
            <th>
                Nome Pokémon
            </th>
            <th>
                Detalhes
            </th>
            <th>
                Alterar Pokémon
            </th>
    </thead>
    <tbody style="text-align:center">
        @foreach (Pokemon item in Model)
        {
            <tr>
                <td>
                    @item.PokemonId
                </td>
                <td>
                    <img height="60" src="@item.Url_Sprite_front_default" alt="Sprite Frontal" />
                </td>
                <td>
                    @item.Nome
                </td>
                <td>
                    @Html.ActionLink("Detalhes", "Detalhes", "Pokemon", new { id = item.PokemonId, usuarioId = ViewBag.Usuario.UsuarioID }, new { @class = "btn btn-outline-primary" })
                </td>
                <td>
                    @Html.ActionLink("Alterar Pokémon", "AlterarPokemon", "Usuario", new { pokemonId = item.PokemonId, usuarioId = ViewBag.Usuario.UsuarioID }, new { @class = "btn btn-outline-primary" })

                </td>
            </tr>

        }
    </tbody>
</table>